/**
 * @author Erik Desjardins
 * See LICENSE file in root directory for full license.
 */

'use strict';

var path = require('path');

module.exports = function() {};

module.exports.pitch = function(request) {
	var callback = this.async();

	var relativeContext = path.dirname(request);
	var extension = '.' + request.split('.').slice(-1)[0];

	// add context dependency so new files are picked up
	this.addContextDependency(relativeContext);

	this.fs.readdir(this.context, function(err, files) {
		if (err) return callback(err);

		var matchingFiles = files
			.filter(function(filename) {
				return filename.endsWith(extension);
			})
			.map(function(filename, i) {
				return {
					name: filename,
					id: '_' + i
				};
			});

		var header = '/* generated by sibling-loader */';

		var importStatements = matchingFiles
			.map(function(info) {
				return 'import * as ' + info.id + ' from ' + JSON.stringify('.' + path.sep + path.join(relativeContext, info.name)) + ';';
			})
			.join('\n');

		var exportStatement = 'export default { ' + matchingFiles
				.map(function(info) {
					return JSON.stringify(info.name) + ": " + info.id;
				})
				.join(', ') + ' };';

		callback(null, [header, importStatements, exportStatement].join('\n'));
	});

	return '';
};
